### ISSUE TITLE
建议依赖图带有文件路径

### ISSUE THREAD

**Issue by 17097231932** [sz-p/vscode-dependencyGraph#10]
大型项目中会有很多不同目录但同名的文件，所以会出现一些很奇怪的现象，并且阅读源代码的时候就会有很多疑问。所以我建议文件名显示时以主文件的相对路径去显示。

**Comment by sz-p** [comment]
非常不错的建议，但考虑到有些项目的文件路径相对于根路径过深。直接以相对路径作为显示名称，该名称将会过长，可能不太利于阅读。

这里会将文件的相对路径以`title`的形式在画布中，以及`文件信息框`中展示。

![image](https://user-images.githubusercontent.com/14040327/119223680-4de97500-bb2d-11eb-8c39-7e53df5472b0.png)

**Comment by 17097231932** [comment]
<del>可以在webview界面上也添加title属性</del>

看了一下**源代码**，好像是用 [`d3`](https://gthub.com/d3/d3) 渲染的 `svg`, 应该是没有办法去添加 title 的

**Comment by sz-p** [comment]
> ~可以在webview界面上也添加title属性~
> 
> 看了一下**源代码**，好像是用 [`d3`](https://gthub.com/d3/d3) 渲染的 `svg`, 应该是没有办法去添加 title 的

d3 添加 `title` 的方式并不复杂[demo](https://stackblitz.com/edit/set-title-to-svg?file=index.html), 不过应该有更好的方式来做提示，详情等跟新之后见代码吧。

**Comment by sz-p** [comment]
afe900683ecb0898b90a61e1fe3099b85b8c049a

**Comment by sz-p** [comment]
最终还是选择了使用`title`的来实现，简单，快速，带主题。 详情见 afe900683ecb0898b90a61e1fe3099b85b8c049a 该功能已于1.1.1版本发布
