### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by wyswill** [sz-p/vscode-dependencyGraph#13]
希望路径别名能自动根据jsconfig和tsconfig中的path配置自动添加

**Comment by sz-p** [comment]
接下来
1. 尝试从`./tsconfig` `.compilerOptions.paths` 来获取resolve
![image](https://user-images.githubusercontent.com/14040327/120754821-c1cd4980-c53f-11eb-8515-6272d6595e92.png)

2. 尝试在`./**/webpack.config.js`  `.resolve.alias`  来获取resolve
![image](https://user-images.githubusercontent.com/14040327/120759320-7ddd4300-c545-11eb-9c7a-9c5a8b6cbbe8.png)

但由于打包工具五花八门`tsc` `webpack` `rollup`等等 `resolve path` 配置项存在的路径并不相同，这里不能保证一定能正确的获取路径别名。

如果可以话请提供下您的别名配置环境、或配置文件。这里会优先支持您当前的情况。

最后，非常感谢您的反馈，这对我帮助很大，祝工作愉快。

**Comment by wyswill** [comment]
你可以从标准的tsconfig的paths入手。jsconfig和tsconfig差不多，两个都一样，
![image](https://user-images.githubusercontent.com/26476386/120760534-cc3f1180-c546-11eb-8b49-9eeda8eabfac.png)
这是我的tsconfig文件
![image](https://user-images.githubusercontent.com/26476386/120760606-df51e180-c546-11eb-82b0-66d0b4513a32.png)
这是我同步tsconfig到webpack中的alias的方法。你可以参考一下

**Comment by wyswill** [comment]
或者你可以做一个你自己的中间path  json文件。把tsconfig、jsconfig和各种打包工具的配置文件都处理成统一的数据结构。也可以做成插件的模式，让用户自己定义config的数据结构。

**Comment by sz-p** [comment]
> 或者你可以做一个你自己的中间path json文件。把tsconfig、jsconfig和各种打包工具的配置文件都处理成统一的数据结构。也可以做成插件的模式，让用户自己定义config的数据结构。

目前有两种方式可以修改别名属性，一是通过`webview` GUI的方式人工输入，另一个可直接修改插件目录下(`.dependencygraph/setting.json`) setting文件。大致结构如下：
```json
{
  "entryFilePath": "\\src\\main.js",
  "alias": {
    "@": "./src"
  },
  "resolveExtensions": [
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".vue",
    ".scss",
    ".less"
  ]
}
```

直接修改“alias”字段即可。

**Comment by sz-p** [comment]
鉴于您目前的需求，这里会优先增加对`tsconfig`和`jsconfig`的路径别名提取工作。之后会陆续新增对其余打包工具配置项的支持。

**Comment by sz-p** [comment]
简单增加了对 ts js config中的paths的识别。详情见：d07f2776cad2851cfbf56cf789a03a97a37c3310 测试用例见：ece60a0a24da121a8e01ecb06ef39903f424b70c，目前还很简陋，遇到同类需求后会逐步优化。
