### ISSUE TITLE
V1.1.5总是在等待数据？今天跑了10小时，不断的右侧打开新窗口。。

### ISSUE THREAD

**Issue by 050602** [sz-p/vscode-dependencyGraph#20]
看改动日志是说修复了等待数据的问题，，，我是第一次使用，我不知道具体需要多少时间去抓取数据，。，

反正我等了一个中午到晚上10点。。。还一直在右侧打开新窗口，然后等待数据，然后新窗口，又等待数据

**Comment by 050602** [comment]
然后看VSCODE CPU一直占用整机30%这样，

**Comment by sz-p** [comment]
> 看改动日志是说修复了等待数据的问题，，，我是第一次使用，我不知道具体需要多少时间去抓取数据，。，
> 
> 反正我等了一个中午到晚上10点。。。还一直在右侧打开新窗口，然后等待数据，然后新窗口，又等待数据

非常感谢您的反馈！

出现这种情况的可能性如下：

1.  程序包含未知BUG，例如分析依赖项时存在死循环？
2. 被分析程序过于庞大（项目规模类似与或大于[ECharts](https://github.com/apache/echarts)，导致文件依赖关系过大）文件依赖关系从`服务端`向`前端展示页`传递时产生阻塞。
3. 插件异步程序异常，`服务端`已向`前端展示页`发送数据但`前端展示页`未能正确接收。

![image](https://user-images.githubusercontent.com/14040327/159157334-46c9c9b5-51cc-4c25-9569-04d1d3183a98.png)
如果左侧`treeView`中已经出现具体文件但右侧`webview`中显示等待中则大概率为情况3

如果是已开源项目或可开源项目可告知`repo`地址（如果是非开源项目可仅保留文件引用关系）。这将非常有助于开发者去定位具体问题。

> ps：通常分析依赖树并将数据发送至前端展示页不会超过10min，如果超时仍未获取数据，关闭插件并重新打开或许比继续等待更容易获得预期结果。

**Comment by sz-p** [comment]
> 然后看VSCODE CPU一直占用整机30%这样，

如果该占中为VsCode整体CPU占用则可能为，VsCode本身的CPU占用，VsCode其余插件占用等。

**Comment by 050602** [comment]
你好~在左侧栏里，什么东西都没有显示出来，就一直新开窗口，

今天换到别的电脑尝试，结果也是一样的
![image](https://user-images.githubusercontent.com/26473448/159163978-b35ec258-8ec8-460d-8f16-bad321cce36a.png)

**Comment by 050602** [comment]
![image](https://user-images.githubusercontent.com/26473448/159164539-1360a9cf-6f4e-4aa4-a5f4-604009f13dbe.png)
ran'h
然后又冒出来一个，
我已经开了美国的VPN了

项目规模比较小，大概才开发了三个月

死循环我就不敢肯定了， QAQ

**Comment by sz-p** [comment]
请问方便展示下您的`package.json`以及`package.json`中`main`指向的文件吗？

**Comment by 050602** [comment]
package.json
`{
  "name": "app",
  "version": "1.0.0",
  "main": "main.js",
  "bin": {},
  "dependencies": {
    "@appland/appmap-agent-js": "^10.0.1",
    "nodejs": "0.0.0",
    "save-dev": "0.0.1-security",
    "uglify-js": "^3.13.10",
    "uglifyjs": "^2.4.11",
    "webpack-dev-server": "^3.11.0"
  },
  "devDependencies": {
    "awesome-typescript-loader": "^5.2.1",
    "http-server": "^0.12.3",
    "source-map-support": "^0.5.21",
    "strip-sourcemap-loader": "0.0.1",
    "ts-node": "^10.0.0",
    "typescript": "^4.2.3",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "scripts": {
    "dev": "webpack --mode development",
    "server": "webpack -dev-server --open",
    "start": "webpack",
    "poststart": "node copyJsFile2.js output ../client/Assets/Assets/ts",
    "watch": "webpack --watch",
    "toU3D": "webpack",
    "posttoU3D": "uglifyjs output/main.js -o output/main.js && node copyJsFile2.js output ../client/Assets/Assets/ts"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "devServer": {
    "contentBase": "src"
  }
}
`

setting.json
`{
  "entryFilePath": "./Script/view/TSMain.ts",
  "resolveExtensions": [
    ".ts"
  ],
  "alias": {
    "Script": "./Script"
  }
}`

目录结构
![image](https://user-images.githubusercontent.com/26473448/159167170-fb392661-6422-4d71-9636-3706af69b492.png)

用的typescript， 需要把package.json 指向 TSMain.ts 吗？

main.js,是一个把所有代码合并起来的JS

**Comment by 050602** [comment]
[https://github.com/050602/Unity-PuerTS-ECS/tree/main/TsProj](url)
我的项目结构，与此仓库大概一致，但是会填充了更多代码

**Comment by sz-p** [comment]
`"main": "main.js"`  当前目录下似乎并没有`main.js`这里应该为'output/main.js'。 如果当前目录下未发现入口文件插件应该会提示异常的，但现在未提示可能这里存在问题，我去debug一下。

**Comment by 050602** [comment]
感谢你的回答，我尝试一下使用output/main.js

**Comment by 050602** [comment]
setting.json
`{
  "entryFilePath": "./Script/view/TSMain.ts",
  "resolveExtensions": [
    ".ts",".js"
  ],
  "alias": {
    "Script": "./Script"
  }
}`
之前那里，已经是显式指向TSMain了，，，又尝试了一下修改package.json ,又执行了一次，还是在新开窗口，，QAQ

**Comment by sz-p** [comment]
> setting.json `{ "entryFilePath": "./Script/view/TSMain.ts", "resolveExtensions": [ ".ts",".js" ], "alias": { "Script": "./Script" } }` 之前那里，已经是显式指向TSMain了，，，又尝试了一下修改package.json ,又执行了一次，还是在新开窗口，，QAQ

如果是windows系统请尝试`  "entryFilePath": "\\src\\index.js"`

**Comment by 050602** [comment]
老哥，还是失败了，，，我。。再起不能了。。。
还是一直右边打开窗口

**Comment by sz-p** [comment]
> 老哥，还是失败了，，，我。。再起不能了。。。 还是一直右边打开窗口

我会尝试修复一版 明天您可以尝试下新版本

**Comment by 050602** [comment]
您好，您的邮件我已经收到，现在是夜间，不方便回复您的邮件，我将尽快回复您。

**Comment by sz-p** [comment]
> [https://github.com/050602/Unity-PuerTS-ECS](url) 我的项目结构，与此仓库里的TSProj大概一致，但是会填充了更多代码

我尝试了下该项目 问题仍未解决。

**Comment by 050602** [comment]
早上好，感谢你的帮助，期待你的修复~

**Comment by sz-p** [comment]
定位了下问题。

请查看当前项目下`tsconfig.json`。

origin

```json
{
  "compilerOptions": {
    "skipLibCheck": true,
		// "allowSyntheticDefaultImports": true,
    // "experimentalDecorators": true, 
    "target": "esnext",
    "module": "commonjs",
    "jsx": "react",
    "sourceMap": true,
    "noImplicitAny": true,
    "typeRoots": [
      "../client/Assets/Puerts/Typing",
      "../client/Assets/Gen/Typing",
      "./node_modules/@types"
    ],
    "outDir": "output",
    
  }
}
```


new

```json
{
  "compilerOptions": {
    "skipLibCheck": true,
    "target": "esnext",
    "module": "commonjs",
    "jsx": "react",
    "sourceMap": true,
    "noImplicitAny": true,
    "typeRoots": [
      "../client/Assets/Puerts/Typing",
      "../client/Assets/Gen/Typing",
      "./node_modules/@types"
    ],
    "outDir": "output"
  }
}
```

原始的`tsconfig.json`并不是严格意义上的`json`格式。导致`json`文件解析出错程序未向下进行。该部分已着手进行修复。
![image](https://user-images.githubusercontent.com/14040327/159199085-0d4bc970-2997-4e43-af89-411391a79354.png)

可手动修改`tsconfig.json`格式以正确分析文件

**Comment by sz-p** [comment]
> 作者你好，我尝试把tsconfig.json 的注释行移除，但是问题依然存在，还是会在右侧打开新窗口
> 
> ![image](https://user-images.githubusercontent.com/26473448/159268176-ad4090c4-c84b-4789-ad71-d7afcdc7d720.png)

把行末的逗号去掉试试？ `"outDir": "output"` 今天晚上我修一版

**Comment by 050602** [comment]
去掉了，问题依旧，，QAQ

**Comment by sz-p** [comment]
可以试下 1.1.7 解决了读取json异常的问题。

**Comment by 050602** [comment]
作者你好，我更新到了1.1.7了，仍然没有成功，如果你能正常运行的我github ECS代码，烦请为我提供成功运行的示例，，感谢

**Comment by sz-p** [comment]
@050602 

最新确认的问题为读取异常的JSON导致程序进程阻塞，该问题已在v1.1.7通过使用JSON5解析JSON解决，演示结果如下：

![temp4](https://user-images.githubusercontent.com/14040327/162249361-c29f2a65-6109-49ac-9d08-d98f3f9086c8.gif)

如若仍不能正常执行可能需要更多的信息用于调试。非常感谢您的用心反馈以及大力支持，也非常抱歉给您带来不好的体验。考虑到接下来的繁琐的调试过程会占用大量的时间。为了避免对您过多的打扰，如若没有更进一步的信息，此issue将会被关闭。我会持续关注并跟进。

再次感谢！ 程序的稳定离不开您的用心反馈和大力支持！
