### ISSUE TITLE
Inline requires are not being picked up

### ISSUE THREAD

**Issue by Cilveti** [sz-p/vscode-dependencyGraph#26]
If a require is embeded within a function parameter, like this
` transformCollection('attribute_groups', require('./product_detail/attribute_group'))
`
is not being taken into consideration for the graph.
Maybe there is a configuration for this?

**Comment by sz-p** [comment]
good question!

the inline requires is taken into the graph  in v1.1.9

if you want to know more about that please see https://github.com/palantir/tslint/issues/4296
