### ISSUE TITLE
tsx  语法解析失败

### ISSUE THREAD

**Issue by a1235** [sz-p/vscode-dependencyGraph#28]
入口文件如下：test.tsx，返回的结果只有入口文件
```
import my from './my'

function App(options) {
    return <>hello world</>
}

export default App
```
![1651824648(1)](https://user-images.githubusercontent.com/29188013/167093234-f77d9f0c-950e-4ed4-999d-dba3b6522b35.png)
函数直接return null 的话是正常的

**Comment by sz-p** [comment]
update on v1.1.10

**Comment by sz-p** [comment]
the typescript parser in recast in not support `tsx`. 

using `babel-ts` parser to parse for now

https://github.com/benjamn/recast/pull/535
