### ISSUE TITLE
How do you get to webview?

### ISSUE THREAD

**Issue by king612** [sz-p/vscode-dependencyGraph#30]
I don't see how you get to webview in VS Code.  Where is the "view page"?  I have installed v1.1.11, and I don't see any of this in VS Code.

Thanks

**Comment by sz-p** [comment]
After installed this extension you should see 
<img width="47" alt="image" src="https://user-images.githubusercontent.com/14040327/173478895-5e8238ea-e34f-41c0-b7a1-6ceb5f376b79.png">
in [activitybar](https://code.visualstudio.com/api/ux-guidelines/activity-bar)

After clicked this icon you should see 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/14040327/173479557-a2879f40-cc85-4126-b693-ac49c4e169e7.png">
`dependence graph view page` in [webview](https://code.visualstudio.com/api/extension-guides/webview)

If not see this, please give me some information like your `screenshot` `systematic platform environment`.

I will see is there have a bug or not

**Comment by king612** [comment]
Yes, I was missing the icon in the activity bar somehow.  Got it work now -
wow!  What a great piece of work.  Thank you for building this.

And thank you for getting back to me.
