### ISSUE TITLE
Dependency graph doesn't show

### ISSUE THREAD

**Issue by hulkaroyJouraboeva** [sz-p/vscode-dependencyGraph#34]
Hi,

Downloaded the extension followed the steps, configured the settings, but even after some and few attempts at trying different things dependency graph doesn't show in the webview panel. It's either just black screen, loading, or just throws this error "NO_WEBVIEW_PANEL: No webview panel", all seen in the screenshots.

![Screen Shot 2022-08-09 at 2 12 49 AM](https://user-images.githubusercontent.com/86935670/183578118-55c86ba7-a74e-44e0-8053-67137237c692.png)
![Screen Shot 2022-08-09 at 2 11 08 AM](https://user-images.githubusercontent.com/86935670/183578120-f9aa8f41-d168-4291-b085-14b90a4df427.png)
![Screen Shot 2022-08-09 at 2 09 54 AM](https://user-images.githubusercontent.com/86935670/183578123-e920ca3b-7d15-4370-8dfb-e437960d34a9.png)

**Comment by sz-p** [comment]
Try refresh graph and reopen webview ?

![image](https://user-images.githubusercontent.com/14040327/183932239-7d091b8b-a9e4-46a7-8be6-533b62385465.png)

**Comment by sz-p** [comment]
If not work I need some information like 

- OS:
- Extension Version
- VSCode Version

**Comment by hulkaroyJouraboeva** [comment]
I got it now, thank you!

**Comment by hulkaroyJouraboeva** [comment]
I got it now, thank you!
