### ISSUE TITLE
Vue Script Setup is not recognized for imports

### ISSUE THREAD

**Issue by hinogi** [sz-p/vscode-dependencyGraph#48]
no children are detected if you use imports in vue sfc script setup.

**Comment by sz-p** [comment]
can you show me some code?  I will make a test case and fix this.

**Comment by hinogi** [comment]
```html
<template lang=pug">
.someLonelyDiv
  MyFancyComponent( v-model="msg")
</template>

<script setup lang="ts">
import MyFancyComponent from 'components/my-fancy-component.vue';

const msg = ref('');
</script>
```
```json
// tsconfig.json
{
  "compilerOptions" : {
    ...
    "paths": {
      "components/": ["./src/components"]
    }
  }
}
```
something like this

**Comment by sz-p** [comment]
I made a test case in 959a659

**Comment by sz-p** [comment]
![](https://github.com/sz-p/vscode-dependencyGraph/assets/14040327/9ea886df-344b-44c0-8362-ebb4e029739b)

The `vueComp.vue` file code is:
```html
<template></template>

<script setup lang="ts">
import MyFancyComponent from './my-fancy-component.vue';
</script>

<style>
</style>
```
Please check

1. Do you have `my-fancy-component.vue` file in `components` dir? 
2. Do you need set `Resolve alias` in `setting.json`

![image](https://github.com/sz-p/vscode-dependencyGraph/assets/14040327/d9316d54-f7a9-4a2e-8ba7-fbbd58e44171)


![image](https://github.com/sz-p/vscode-dependencyGraph/assets/14040327/b88c759b-a1f2-42c0-aad0-669e49f3860c)

**Comment by sz-p** [comment]
> ```
> <template lang="pug">
> .someLonelyDiv
>   MyFancyComponent( v-model="msg")
> </template>
> 
> <script setup lang="ts">
> import MyFancyComponent from 'components/my-fancy-component.vue';
> 
> const msg = ref('');
> </script>
> ```
> 
> ```json
> // tsconfig.json
> {
>   "compilerOptions" : {
>     ...
>     "paths": {
>       "components/": ["./src/components"]
>     }
>   }
> }
> ```
> 
> something like this

set 
```json
  "alias": {
    "components/": "./src/components"
  },
```
in 

`./.dependencygraph/setting.json`

**Comment by hinogi** [comment]
> > ```
> > <template lang="pug">
> > .someLonelyDiv
> >   MyFancyComponent( v-model="msg")
> > </template>
> > 
> > <script setup lang="ts">
> > import MyFancyComponent from 'components/my-fancy-component.vue';
> > 
> > const msg = ref('');
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> > // tsconfig.json
> > {
> >   "compilerOptions" : {
> >     ...
> >     "paths": {
> >       "components/": ["./src/components"]
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > something like this
> 
> set
> 
> ```json
>   "alias": {
>     "components/": "./src/components"
>   },
> ```
> 
> in
> 
> `./.dependencygraph/setting.json`

I tried that already and it didn't work

**Comment by hinogi** [comment]
> ![](https://user-images.githubusercontent.com/14040327/284955844-9ea886df-344b-44c0-8362-ebb4e029739b.png)
> 
> The `vueComp.vue` file code is:
> 
> ```
> <template></template>
> 
> <script setup lang="ts">
> import MyFancyComponent from './my-fancy-component.vue';
> </script>
> 
> <style>
> </style>
> ```
> 
> Please check
> 
> 1. Do you have `my-fancy-component.vue` file in `components` dir?
> 2. Do you need set `alias` in `setting.json`
> 
> ![image](https://user-images.githubusercontent.com/14040327/284957081-d9316d54-f7a9-4a2e-8ba7-fbbd58e44171.png)
> 
> ![image](https://user-images.githubusercontent.com/14040327/284957336-b88c759b-a1f2-42c0-aad0-669e49f3860c.png)

this does not have path alias in the import.

**Comment by hinogi** [comment]
I get a `get AST error`

**Comment by sz-p** [comment]
Some `get AST error` is not very important. It is triggered on parse code to AST. 

Have you seen the dependency graph?

**Comment by hinogi** [comment]
yes but it does not use path aliases in your example so that dependency graph still does not exist.

**Comment by sz-p** [comment]
> > > ```
> > > <template lang="pug">
> > > .someLonelyDiv
> > >   MyFancyComponent( v-model="msg")
> > > </template>
> > > 
> > > <script setup lang="ts">
> > > import MyFancyComponent from 'components/my-fancy-component.vue';
> > > 
> > > const msg = ref('');
> > > </script>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```json
> > > // tsconfig.json
> > > {
> > >   "compilerOptions" : {
> > >     ...
> > >     "paths": {
> > >       "components/": ["./src/components"]
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > something like this
> > 
> > 
> > set
> > ```json
> >   "alias": {
> >     "components/": "./src/components"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in
> > `./.dependencygraph/setting.json`
> 
> I tried that already and it didn't work

I will try this, reply to you later.

**Comment by sz-p** [comment]
Sorry.
In my test  ` "components": "./src/components"` is work.
Please try 
```json
  "alias": {
    "components": "./src/components",
     // not work
    "components/": "./src/components/"
  },
```

**Comment by hinogi** [comment]
> Sorry. In my test ` "components": "./src/components"` is work. Please try
> 
> ```json
>   "alias": {
>     "components": "./src/components",
>      // not work
>     "components/": "./src/components/"
>   },
> ```
doesn't work

**Comment by sz-p** [comment]
In this case It is work. https://github.com/sz-p/vscode-dependencyGraph/commit/bec4702305b1ee97febc6b797b315efc8632521d

I don`t know what happened in your repo. 
What I can do is try it on your repo if your it is public.

**Comment by hinogi** [comment]
> In this case It is work. [bec4702](https://github.com/sz-p/vscode-dependencyGraph/commit/bec4702305b1ee97febc6b797b315efc8632521d)
> 
> I don`t know what happened in your repo. What I can do is try it on your repo if it is public.

but in the case mentioned there is no path alias used for the import.

**Comment by hinogi** [comment]
> In this case It is work. [bec4702](https://github.com/sz-p/vscode-dependencyGraph/commit/bec4702305b1ee97febc6b797b315efc8632521d)
> 
> I don`t know what happened in your repo. What I can do is try it on your repo if it is public.

Unfortunately it is not public. And I do not know what is happening but it seems that there is some problem with finding the imports or the children.
