### ISSUE TITLE
建议支持 export { ... } from '...' 形式

### ISSUE THREAD

**Issue by 17097231932** [sz-p/vscode-dependencyGraph#5]
建议支持 export { ... } from '...' 形式，这在开源项目里及其常见

**Comment by sz-p** [comment]
非常棒的建议，感谢反馈，新的功能增加后会在此通知。

**Comment by sz-p** [comment]
发布了 1.1.0 版本 

修复了插件在vscode 1.56.0下不工作的问题
新增了对 export { ... } from '...'模式的识别

感谢反馈，请尝试新版本。
