### ISSUE TITLE
Which file types does this extension support?

### ISSUE THREAD

**Issue by patfinder** [sz-p/vscode-dependencyGraph#50]
### Discussed in https://github.com/sz-p/vscode-dependencyGraph/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **patfinder** January 10, 2024</sup>
Hi,

Thank you for the very useful extension. This helps review and learn the code very efficiently.

One question from me. I see that the repo introduction show the extension works with TS file (and properly JS too). But how about other file types?

I couldn't find any information about the supported file types in the documentation. Could you kindly add this information to prevent any confusion among users and save them time from unnecessary checks?

Thank you for your attention to this matter, and please keep up the excellent work!</div>

**Comment by sz-p** [comment]
It has already been displayed in readme.

## 📝 Supported file

| File type | .js  | .ts  | .jsx | .tsx | .vue | .scss | .less | .sass | .py  | .php | .go  |
| -------- | ---- | ---- | ---- | ---- | ---- | ----- | ----- | ----- | ---- | ---- | ---- |
| Support status | ✅    | ✅    | ✅    | ✅    | ✅    | ✅     | ✅     | ✅     |      |      |      |

**Comment by patfinder** [comment]
Thank @sz-p
